name: permission_handler_windows
description: Permission plugin for Flutter. This plugin provides the Windows API to request and check permissions.
version: 0.1.2
repository: https://github.com/localsend/permission_handler_windows_noop

flutter:
  plugin:
    implements: permission_handler
    platforms:
      windows:
        pluginClass: PermissionHandlerWindowsPlugin

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: any

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
